### ISSUE TITLE
Definition to the reads which are not fully converted by bisulfite treatment? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [BSSeeker/BSseeker2#12]
Hi Dr. Weilong, 

Where I can find the definition to the reads which are not fully converted by bisulfite treatment? 

I notice it before, however, I can not find it again when I need it. 

Thanks. 

Shicheng

**Comment by guoweilong** [comment]
Dear Shicheng,


The parameter "--XS=XS_FILTER" of bs_seeker2-align.py is to mark which reads are not fully converted by bisulfite treatment. (in BAM file, reads with tag XS:i:1)
The parameter "-x, --rm-SX" of bs_seeker2-call_methylation.py is to remove the reads which are marked as not fully converted.


You can also read our paper to see how the filtering funciton works.
http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-14-774


--
Best,
Weilong



At 2016-11-15 02:11:08, "Shicheng Guo" <notifications@github.com> wrote:


Hi Dr. Weilong,

Where I can find the definition to the reads which are not fully converted by bisulfite treatment?

I notice it before, however, I can not find it again when I need it.

Thanks.

Shicheng
