### ISSUE TITLE
Dataset for testing

### ISSUE THREAD

**Issue by bandapanda** [BSSeeker/BSseeker2#15]
Hello,

I tried to find datasets on the site you gave in your publification (http://pellegrini.mcdb.ucla.edu/BS_Seeker2/) but there I couldn't find anything.  Could you please send me a web address where I can find those datasets?

Thanks in advance,
Tamara

**Comment by guoweilong** [comment]
Hi Tamara,

It seems the website is under mantaining.

**Comment by guoweilong** [comment]
Hi @bandapanda ,

**Comment by guoweilong** [comment]
Hi @bandapanda ,

It seems that the site is under maintaining.

Currently, you can try to download the data from this temporary mirror site [http://guoweilong.github.io/BS_Seeker2/index.html](http://guoweilong.github.io/BS_Seeker2/index.html).

Let me know if you need further help.

Best,
Weilong

**Comment by bandapanda** [comment]
Hi @guoweilong,

Thank you very much.

Best,
Tamara
