### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by hyystvar** [BSSeeker/BSseeker2#20]
I do not find the step of removing PCR duplication in your RRBS pipline. why?

**Comment by guoweilong** [comment]
We don't recommend you to use PCR duplication in RRBS, as in RRBS, reads from one region usually start from same position (such as C-CCG end), and even different moleculars would have same sequence. Thus remove duplicates sequence in RRBS is not equal to remove PCR duplication reads.

Best,
Weilong
