### ISSUE TITLE
ERROR: Index DIR "_rrbs_150_400.." cannot be found in /home/knight05/software/BSseeker2-2.1.1/bs_utils/reference_genomes.         Please run the bs_seeker2-build.py to create it with the correct parameters for -g, -r, --low, --up and --aligner.

### ISSUE THREAD

**Issue by connorhknight** [BSSeeker/BSseeker2#28]
Hi, I am receiving the error above when trying to use the aligner. I have run the bs_seeker2-build.py script on my reference genome. I have also been specifying the up and low bound too. Any advice?

**Comment by guoweilong** [comment]
Could you paste your full commands for building the index and alignment step?

**Comment by connorhknight** [comment]
python bs_seeker2-build.py -file /home/knight05/data/BSeeker_ref/ --aligner=bowtie2 -p <path to bowtie2> -r -l 150 _u 400

python bs_seeker2-align.py -1 /store/LevelOne/ATAC_FFPE/METHYLATION/RRBS/UCL_pilot_01/diversity_trimmed/TR0008_S6_R1_001_val_1.fq_trimmed.fq.gz -2 /store/LevelOne/ATAC_FFPE/METHYLATION/RRBS/UCL_pilot_01/diversity_trimmed/TR0008_S6_R3_001_val_2.fq_trimmed.fq.gz  -g <path to genome> -r


________________________________

**Comment by guoweilong** [comment]
As you have built specific RRBS index, you need to use same "-r -L -U" parameters for alignment step.

python bs_seeker2-align.py -1 /store/LevelOne/ATAC_FFPE/METHYLATION/RRBS/UCL_pilot_01/diversity_trimmed/TR0008_S6_R1_001_val_1.fq_trimmed.fq.gz -2 /store/LevelOne/ATAC_FFPE/METHYLATION/RRBS/UCL_pilot_01/diversity_trimmed/TR0008_S6_R3_001_val_2.fq_trimmed.fq.gz -g <path to genome> -r -L 150 -U 400.



Best,
--
Weilong



At 2019-07-12 20:34:03, "Connor Knight" <notifications@github.com> wrote:
python bs_seeker2-build.py -file /home/knight05/data/BSeeker_ref/ --aligner=bowtie2 -p <path to bowtie2> -r -l 150 _u 400

python bs_seeker2-align.py -1 /store/LevelOne/ATAC_FFPE/METHYLATION/RRBS/UCL_pilot_01/diversity_trimmed/TR0008_S6_R1_001_val_1.fq_trimmed.fq.gz -2 /store/LevelOne/ATAC_FFPE/METHYLATION/RRBS/UCL_pilot_01/diversity_trimmed/TR0008_S6_R3_001_val_2.fq_trimmed.fq.gz -g <path to genome> -r


________________________________
