### ISSUE TITLE
outputs of bs_seeker2-build.py

### ISSUE THREAD

**Issue by kwanghoon821** [BSSeeker/BSseeker2#38]
Hi, I'm trying to use BSSeeker2.

First, I used bs_seeker2-build.py to build the index.

python bs_seeker2-build.py \
-f path/to/ref.fasta \
--aligner=bowtie2 \
-d outputdir.

I got many outputs(3377) 
C_C2T.fa
C_G2A.fa
chr1.data
chr1_GL383518v1_alt.data
chr1_GL383519v1_alt.data
and so on
Is this normal?

Anyway, I tried to align using the index.

I have four ".fa" format outputs
C_C2T.fa
C_G2A.fa
W_C2T.fa
W_G2A.fa

What should I use file for alignment?

**Comment by guoweilong** [comment]
Yes, it is normal. Just keep these files, and specify the folder if not build using default parameter.

Best,
Weilong Guo

**Comment by kwanghoon821** [comment]
@guoweilong 
Thank you!
