### ISSUE TITLE
bs_seeker2-call_methylation.py has error with merged bam file

### ISSUE THREAD

**Issue by hmkim** [BSSeeker/BSseeker2#4]
check this issue.

When I run the calling program in bs_seeker2 (bs_seeker2-call_methylation.py) with my bam file (all chromosome), I got the error. 

TypeError: string indices must be integers

I check the pr.query_position (variable) and I found the the value is None.
so, I change the code.

Could you confirm this solution or any other solution?

<img width="669" alt="2015-11-10 08 19 57" src="https://cloud.githubusercontent.com/assets/4966343/11052403/f0273e5a-879a-11e5-9fa3-5d7aefe997bf.png">

**Comment by BSSeeker** [comment]
@hmkim 
Is this error for all the reads, or only for some reads?
What's your pysam version?
Thanks.

**Comment by hmkim** [comment]
pysam version is 0.8.3

Well, This error is for some reads.

Sorry for my late reply.

**Comment by alena54** [comment]
Hi,
When i'm running bs_seeker2-call_methylation.py(see below the sh file),i'm getting error.Can you please rectify the error.

Methylation_call.sh
python2.7 bs_seeker2-call_methylation.py -i /BS-Seeker_align.bam -o Methylation_call --db /BSseeker2master/bs_utils/reference_genomes/Homo_sapiens.GRCh37.75.dna.toplevel.fa_bowtie2

Error Msg:
BS-Seeker2 v2.0.8 - Sept 5, 2014
[2015-12-23 12:40:17] sorting BS-Seeker alignments
[2015-12-23 13:12:02] indexing sorted alignments
[2015-12-23 13:14:46] calculating methylation levels
[2015-12-23 13:14:57] Processing chromosome: 1
Traceback (most recent call last):
  File "bs_seeker2-call_methylation.py", line 267, in <module>
    read_nuc = pr_alignment.seq[pr.query_position]
TypeError: string indices must be integers, not NoneType.

Thank you so much for the time and consideration.

**Comment by guoweilong** [comment]
Hello,

It seems a pysam version problem. As many people reported our original version did not support new pysam, I updated this, but it seems your version still not work well.
May I know the version of your pysam?



Best,
Weilong






At 2015-12-29 14:19:27, "alena54" <notifications@github.com> wrote:


Hi,
When i'm running bs_seeker2-call_methylation.py(see below the sh file),i'm getting error.Can you please rectify the error.

Methylation_call.sh
python2.7 bs_seeker2-call_methylation.py -i /BS-Seeker_align.bam -o Methylation_call --db /BSseeker2master/bs_utils/reference_genomes/Homo_sapiens.GRCh37.75.dna.toplevel.fa_bowtie2

Error Msg:
BS-Seeker2 v2.0.8 - Sept 5, 2014
[2015-12-23 12:40:17] sorting BS-Seeker alignments
[2015-12-23 13:12:02] indexing sorted alignments
[2015-12-23 13:14:46] calculating methylation levels
[2015-12-23 13:14:57] Processing chromosome: 1
Traceback (most recent call last):
File "bs_seeker2-call_methylation.py", line 267, in
read_nuc = pr_alignment.seq[pr.query_position]
TypeError: string indices must be integers, not NoneType.

Thank you so much for the time and consideration.

**Comment by alena54** [comment]
Hi ,
I'm using Python2.7 and pysam '0.8.3'

**Comment by alena54** [comment]
Hi ,
I'm using Python2.7 and pysam '0.8.3'
Thanks.

**Comment by BSSeeker** [comment]
@alena54 @hmkim 

Could you edit the file "bs_seeker2-call_methylation.py", and change the 230th line:

            if pysam.__version__ > "0.8.0" :

to 
            if pysam.__version__ > "0.8.3" :
.

And then let me know if the code works in your machine.
Thanks a lot!

Best,
Weilong

**Comment by BSSeeker** [comment]
@alena54 @hmkim  

Could you edit the file "bs_seeker2-call_methylation.py", and change the 230th line:

        if pysam.__version__ > "0.8.0" :


to

        if pysam.__version__ > "0.8.3" :


And then let me know if the code works in your machine.
Thanks a lot!

Best,
Weilong

**Comment by BSSeeker** [comment]
@alena54 
I just updated the call_methylation as suggested by @hmkim. Can you updated your local version, and see if it works?

**Comment by alena54** [comment]
Hi ,
Thank you so much.
I have changed the code as you said but again other error generated.

Traceback (most recent call last):
  File "bs_seeker2-call_methylation.py", line 233, in <module>
    pr_qpos =pr.qpos
AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute
'qpos'

Thanks alot

**Comment by guoweilong** [comment]
Hello,

I might not clear in last email.


Could you just replace the new bs_seeker2-call_methylation.py from the github? And DO NOT change the code any more.
I thought it was the version problem, but from @hmkim, it seems a problem with new version of pysam.


So please change the code back to:


    if pysam.__version__ >"0.8.0" :



And do NOT change ti to:


    if pysam.__version__ >"0.8.3" :





Best,
Weilong

--

Integrated Science Building 538
Peking University, 100871
Beijing, China
Homepage:
http://guoweilong.github.io/




At 2015-12-30 13:12:10, "alena54" <notifications@github.com> wrote:
Hi ,
Thank you so much.
I have changed the code as you said but again other error generated.

Traceback (most recent call last):
File "bs_seeker2-call_methylation.py", line 233, in <module>
pr_qpos =pr.qpos
AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute
'qpos'

Thanks alot

**Comment by alena54** [comment]
Hi

Ya sure i will replace the new bs_seeker2-call_methylation.py from the
github.
Thank you so much.

**Comment by alena54** [comment]
Hi

Sorry for the late reply.
Now it working fine and got the result for methylation_call.
Thanks.

**Comment by alena54** [comment]
Hi,

During Alignment steps, In Output no. of cycles are shown and i guess it
varies on size of file or bases.can you please tell me in what basis the
cycles are counted.if you could a brief explanation about it.
For example:i ran three sample data and in that in one it ran 17 cycles
,second 15 cycles and third 275 cycles.Please guide me.
Thank you  for time and consideration.

**Comment by guoweilong** [comment]
@alena54 Hi, sorry just noticed your lastest comment.

The cycle indicate the "cycle" during Illumina sequencing, corresponding to number of base in your sequenced reads.

If your read is 150bp SE, then  -s 11 -e 140 would cut 10bp from both 5' and 3' ends.

Weilong
