### ISSUE TITLE
Compatibility with bismark?

### ISSUE THREAD

**Issue by weishwu** [BSSeeker/BSseeker2#46]
I wonder if I can run `bs_seeker2-call_methylation.py` with Bismark alignments. Is there any tweaking I need to do or it's simply not recommended?
Thanks.

**Comment by guoweilong** [comment]
Hi Weisheng,

bs_seeker2-call_methylation.py was designed for BS-Seeker2's alignment, and is not compatible with Bismark alignment.

Weilong



At 2022-04-22 04:25:44, "Weisheng Wu" ***@***.***> wrote:

I wonder if I can run bs_seeker2-call_methylation.py with Bismark alignments. Is there any tweaking I need to do or it's simply not recommended?
Thanks.

**Comment by weishwu** [comment]
That's what I thought. Thanks!
