### ISSUE TITLE
Unique alignment

### ISSUE THREAD

**Issue by buyejue** [BSSeeker/BSseeker2#5]
If I want allowed random mapping of reads with multiple genomic hits, is there an argument I should supply directly to Bowtie2 (via BS Seeker 2's command line option) ? 

Thanks.

**Comment by guoweilong** [comment]
BS-Seeker2 does report reads which have multiple genomic hits. You can specific parameter "-M" for bs_seeker2-align.py to save the reads information.

However, the information about multiple alignments (where they could be aligned) are not reported, as being discarded when reporting unique best hit.

Best,
Weilong Guo


At 2016-04-26 19:12:47, "buyejue" <notifications@github.com> wrote:


If I want allowed random mapping of reads with multiple genomic hits, is there an argument I should supply directly to Bowtie2 (via BS Seeker 2's command line option) ?

Thanks.
