### ISSUE TITLE
Base Qualities

### ISSUE THREAD

**Issue by aheravi** [BSSeeker/BSseeker2#7]
Hi,
In BSseeker2, it seems to me there is no base quality attached to the reads. Is that true?

samtools view EX0001_bsSeeker2.kayrotypic.sorted.ReadGroup.bam | cut -f11 | head -1
*

**Comment by BSSeeker** [comment]
Yes, you are right.

BS-Seeker2 would not consider base quality, but in fact consider number of mismatches.

From our experiences, no significant difference to include the quality or not when mapping.

You may trace back to fastq/qseq file using reads ID for base quality information.
And I would like to hear from you if any concern on this issue or related.


Best,
Weilong






在 2016-05-12 06:05:30，"aheravi" <notifications@github.com> 写道：


Hi,
In BSseeker2, it seems to me there is no base quality attached to the reads. Is that true?

samtools view EX0001_bsSeeker2.kayrotypic.sorted.ReadGroup.bam | cut -f11 | head -1
*

**Comment by aheravi** [comment]
Well, I am trying to run BisSNP on the bam and need those base qualities for the recalibration process.
Thanks,
Ali

**Comment by BSSeeker** [comment]
Hi Ali,

The easiest way is to set the column as best for all bases.

Also to retrieve the raw data for quality.

If BS-Seeker2 supports quality in the future, I'll let you know.



Best,
Weilong


At 2016-05-12 08:00:37, "aheravi" <notifications@github.com> wrote:


Well, I am trying to run BisSNP on the bam and need those base qualities for the recalibration process.
Thanks,
Ali
