### ISSUE TITLE
Remove overlapped region between two mates for paired-end reads

### ISSUE THREAD

**Issue by haodongchen** [BSSeeker/BSseeker2#8]
It seems that now BSseeker2 supports the removal of overlapped regions between two paired-end reads (--rm-overlap) in bs_seeker2-call_methylation.py. Does it only remove the overlapped region between reads, or completely remove the second read if overlapped with the first one?

**Comment by guoweilong** [comment]
Haodong,


BS-Seeker2 has been supporting --rm-overlap for a long time.


It will remove overlapped region between reads, NOT removing whole reads.


Best,
Weilong




At 2016-05-13 05:10:13, "Haodong Chen" <notifications@github.com> wrote:


It seems that now BSseeker2 supports the removal of overlapped regions between two paired-end reads (--rm-overlap) in bs_seeker2-call_methylation.py. Does it only remove the overlapped region between reads, or completely remove the second read if overlapped with the first one?

**Comment by haodongchen** [comment]
Thank you for clarification, Weilong. Could you please update the README.md file to reflect this change? Thanks!

**Comment by guoweilong** [comment]
Thanks for this suggestion. I'll update the README in the next few days.

Best,
Weilong

At 2016-05-14 02:06:06, "Haodong Chen" <notifications@github.com> wrote:


Thank you for clarification, Weilong. Could you please update the README.md file to reflect this change? Thanks!
